### ISSUE TITLE
"Logging from an interrupt is not supported with the DMA-based logger"

### ISSUE THREAD

**Issue by mitchmindtree** [imxrt-rs/imxrt-uart-log#1]
I was just reading through the DMA example and became curious - why this is the case? Is it lack of time to add further support? Or perhaps you come across a bigger design challenge?

I'm particularly curious as I'm anticipating the need to move a lot of data over the teensy's UARTs and after reading a little more about DMA and seeing your benchmarks on the README I figured I should dive in sooner rather than later to see what's involved. I think I'll try to add an `rtic-dma-uart-log.rs` example to the `teensy4-rs` repo sometime soon, but thought I should check in with you about this in the meantime.

**Comment by mciantyre** [comment]
It's mostly vestigial documentation from a previous design. It's also not explicitly tested. But, it should be OK. I'll write an example of it in the 0.2.0 release.

As long as your system is regularly calling `poll()`, you can log from interrupts. It's better to think of it as "from an interrupt handler, you can schedule log messages to be sent the next time you call `poll()`," but that's a mouthful! If you're calling `poll()` in your DMA channel's interrupt handler, your logging responsiveness will be affected by interrupt nesting and interrupt priorities. Exceptions that diverge, like `HardFault`, will need special handling if you're using the async logging, since `HardFault` isn't preempted by your `poll()`ing interrupt.

**Comment by mciantyre** [comment]
We explicitly test this behavior as of the 0.2.0 release. All three examples show logging from a GPT interrupt. We'll maintain this guarantee going forward.
